[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
sha2 = "0.10.5"
libp2p = "0.49.0"
tokio = { version = "1.21.2", features = [
  "io-util",
  "io-std",
  "macros",
  "rt",
  "rt-multi-thread",
  "sync",
  "time",
] }
hex = "0.4"
once_cell = "1.5"
log = "0.4"
pretty_env_logger = "0.4"
